### ISSUE TITLE
4.1

### ISSUE THREAD

**Issue by ashrafalzyoud** [apradillap/redmine_equality_plan#37]
rake aborted!
NameError: uninitialized constant RedmineEqualityPlan::RedminePatch::UserCustomPatch
/home/redmine/4.1/plugins/redmine_equality_plan/init.rb:3:in `block in <top (required)>'
/home/redmine/4.1/config/environment.rb:16:in `<top (required)>'
/home/redmine/.rbenv/versions/2.6.6/bin/bundle:23:in `load'
/home/redmine/.rbenv/versions/2.6.6/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
redmine@172:~/4.1$

**Comment by apradillap** [comment]
Sorry @ashrafalzyoud Can you try again with las README.md update?
Thanks!!

**Comment by ashrafalzyoud** [comment]
rake aborted!
NameError: uninitialized constant RedmineEqualityPlan::RedminePatch::UserCustomPatch
/home/redmine/4.1/plugins/redmine_equality_plan/init.rb:12:in `block in <top (required)>'
/home/redmine/4.1/config/environment.rb:16:in `<top (required)>'
/home/redmine/.rbenv/versions/2.6.6/bin/bundle:23:in `load'
/home/redmine/.rbenv/versions/2.6.6/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by apradillap** [comment]
Hi @ashrafalzyoud. We have solved the mistakes you had. Can you follow the next steps? https://github.com/apradillap/redmine_equality_plan/blob/master/README_EN.md Remember to update the plugin

You should visualize after all the steps:

![captura](https://user-images.githubusercontent.com/69764/93232818-9d93c780-f77a-11ea-9c8a-e081de1e6051.png)
